"""
Car Simulator Engine

This module contains the CarSimulator class that models basic car behavior.
It simulates how RPM, temperature, and throttle position interact with each other.

Key Concepts for Car Tuning:
- RPM (Revolutions Per Minute): How fast the engine crankshaft is spinning
- Throttle Position: How much the throttle is open (0-100%), controlling air/fuel intake
- Engine Temperature: Heat generated by engine operation, critical for engine health
"""


class CarSimulator:
    """
    Simulates a car's engine state and behavior.
    
    This class models the relationship between throttle input and engine response.
    In real cars, pressing the accelerator opens the throttle, allowing more air
    and fuel into the engine, which increases RPM and generates heat.
    """
    
    def __init__(self):
        """
        Initialize the car simulator with default values.
        
        Attributes:
            rpm (int): Engine revolutions per minute
                - Starts at 800 RPM (typical idle speed)
            temperature (float): Engine temperature in Celsius
                - Starts at 60°C (cold engine, typical after starting)
            throttle_position (int): Throttle opening percentage (0-100)
                - 0% = closed (idle)
                - 100% = fully open (maximum power)
            is_running (bool): Whether the engine is running
        """
        self.rpm = 800  # Idle RPM - when engine is running but not accelerating
        self.temperature = 60  # Cold engine temperature in Celsius
        self.throttle_position = 0  # 0-100, where 0 is closed throttle
        self.is_running = True  # Engine is running
    
    def update(self):
        """
        Update the car's state based on current throttle position.
        
        This method simulates how the car responds to throttle input:
        1. When throttle is open (position > 0):
           - RPM increases based on throttle amount
           - Maximum RPM is capped at 7000 (typical redline for many engines)
        2. When throttle is closed (position == 0):
           - RPM slowly decreases back to idle speed (800 RPM)
           - Engine returns to idling state
        3. Temperature increases when engine is working (RPM > idle):
           - Higher RPM = more combustion = more heat
           - Temperature is capped at 105°C (operating temperature)
           - If temperature goes too high, it indicates overheating (not simulated here)
        """
        if self.throttle_position > 0:
            # When throttle is open, increase RPM based on throttle position
            # Formula: RPM increases by throttle_position * 10
            # This simulates how more throttle = more power = higher RPM
            self.rpm += self.throttle_position * 10
            
            # Cap RPM at 7000 (redline - maximum safe engine speed)
            # Exceeding redline can damage the engine
            if self.rpm > 7000:
                self.rpm = 7000
        else:
            # When throttle is closed, RPM should decay back to idle
            # This simulates engine returning to idle speed when not accelerating
            if self.rpm > 800:
                # Decay rate: decrease by 100 RPM each update until reaching idle
                # In reality, this happens due to engine braking and friction
                self.rpm -= 100
                if self.rpm < 800:
                    self.rpm = 800  # Don't go below idle speed
        
        # Temperature management
        # Engine temperature increases when engine is working (RPM above idle)
        if self.rpm > 800:
            # Temperature increases gradually when engine is working
            # Higher RPM = more fuel burned = more heat generated
            self.temperature += 0.5
            
            # Cap temperature at 105°C (normal operating temperature)
            # Most car engines operate optimally around 90-105°C
            if self.temperature > 105:
                self.temperature = 105
    
    def set_throttle(self, position):
        """
        Set the throttle position.
        
        Args:
            position (int): Throttle position percentage (0-100)
                - 0: Throttle closed, engine at idle
                - 50: Half throttle, moderate acceleration
                - 100: Full throttle, maximum power
        
        In real cars, throttle position is controlled by the accelerator pedal.
        The Engine Control Unit (ECU) reads this and adjusts fuel injection
        and air intake accordingly.
        """
        # Clamp throttle position to valid range (0-100)
        if position < 0:
            self.throttle_position = 0
        elif position > 100:
            self.throttle_position = 100
        else:
            self.throttle_position = position

